//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// ShaderTool_KMH.rc에서 사용되고 있습니다.
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_ShaderTool_KMHTYPE          130
#define IDD_EDITBOX                     310
#define IDD_TOOL_SHADER                 311
#define IDD_TOOL_LIGHT                  312
#define IDD_TOOL_INTERACTION            313
#define IDC_BUTTON1                     1000
#define IDC_BUTTON_SHADER_ADDVAR        1000
#define IDC_BUTTON_MAKELIGHTGROUP       1000
#define IDC_BUTTON_SAVE_INTERACTION     1000
#define IDC_EDIT_SHADER_VAR_NAME        1001
#define IDC_EDIT_PERIOD                 1001
#define IDC_EDIT_PL_ANI_PERIOD          1001
#define IDC_LIST_SHADER_VARIABLE        1002
#define IDC_EDIT_POSITION               1002
#define IDC_EDIT_PL_ANI_POSITION        1002
#define IDC_LIST_SHADER_SHADERLIST      1003
#define IDC_EDIT_POSITION2              1003
#define IDC_EDIT_PL_ANI_SPEED           1003
#define IDC_EDIT_POSITION3              1004
#define IDC_EDIT_PL_ANI_CURSPEED        1004
#define IDC_EDIT_SHADER_VAR_FLOAT1      1005
#define IDC_EDIT_POSITION4              1005
#define IDC_EDIT_PL_ANI_CURINDEX        1005
#define IDC_EDIT_SHADER_VAR_FLOAT2      1006
#define IDC_EDIT_PERIOD2                1006
#define IDC_EDIT_MON_ANI_PERIOD         1006
#define IDC_EDIT_SHADER_VAR_FLOAT3      1007
#define IDC_EDIT_POSITION5              1007
#define IDC_EDIT_MON_ANI_POS            1007
#define IDC_EDIT_SHADER_VAR_FLOAT4      1008
#define IDC_EDIT_POSITION6              1008
#define IDC_EDIT_MON_ANI_SPEED          1008
#define IDC_COMBO_SHADER_VAR_TYPE       1009
#define IDC_EDIT_POSITION7              1009
#define IDC_EDIT_MON_ANI_CURSPEED       1009
#define IDC_EDIT_SHADER_LIGHTANGLE      1010
#define IDC_EDIT_SHADER_LIGHTDIRX       1010
#define IDC_EDIT_POSITION8              1010
#define IDC_EDIT_MON_ANI_CURINDEX       1010
#define IDC_CHECK_SHADER_HDR            1011
#define IDC_EDIT_PL_POSX                1011
#define IDC_CHECK_SHADER_MOTIONBLUR     1012
#define IDC_EDIT_PL_ANGLEY              1012
#define IDC_CHECK_SHADER_DOF            1013
#define IDC_EDIT_MON_POSX               1013
#define IDC_CHECK_SHADER_SHADOW         1014
#define IDC_EDIT_MON_ANGLEY             1014
#define IDC_CHECK_SHADER_SSAO           1015
#define IDC_EDIT_PL_POSZ                1015
#define IDC_CHECK_SHADER_EDGEDETECTION  1016
#define IDC_EDIT_PL_POSX2               1016
#define IDC_CHECK_SHADER_LIGHT          1017
#define IDC_EDIT_PL_ANGLEY2             1017
#define IDC_LIST_SHADER_RENDERTARGET    1018
#define IDC_EDIT_MON_POSX2              1018
#define IDC_EDIT_SHADER_TARGETNAME      1019
#define IDC_LIST_SHADER_LIGHT           1019
#define IDC_EDIT_MON_ANGLEY2            1019
#define IDC_COMBO_SHADER_LIGHTTYPE      1020
#define IDC_EDIT_PL_POSZ2               1020
#define IDC_CHECK_SHADER_SHOWTARGET     1021
#define IDC_EDIT_SHADER_LIGHTDIRY       1021
#define IDC_EDIT_PL_POSY                1021
#define IDC_SLIDER_FLOAT1               1022
#define IDC_EDIT_SHADER_LIGHTDIRZ       1022
#define IDC_EDIT_PL_POSY2               1022
#define IDC_SLIDER_FLOAT2               1023
#define IDC_EDIT_SHADER_LIGHTPOSX       1023
#define IDC_EDIT_MON_POSZ               1023
#define IDC_SLIDER_FLOAT3               1024
#define IDC_EDIT_SHADER_LIGHTPOSY       1024
#define IDC_EDIT_MON_POSZ2              1024
#define IDC_SLIDER4                     1025
#define IDC_SLIDER_FLOAT4               1025
#define IDC_EDIT_SHADER_LIGHTPOSZ       1025
#define IDC_EDIT_MON_POSY               1025
#define IDC_SLIDER_LIGHTDIR             1026
#define IDC_SLIDER_LIGHTDIRX            1026
#define IDC_EDIT_MON_POSY2              1026
#define IDC_BUTTON_SHADER_LOAD          1027
#define IDC_BUTTON_LOAD_INTERACTION     1027
#define IDC_BUTTON_SHADER_SAVE          1028
#define IDC_BUTTON_ADD_INTERACTION      1028
#define IDC_SLIDER_LIGHTDIRY            1029
#define IDC_BUTTON_DELETE_INTERACTION   1029
#define IDC_SLIDER_LIGHTDIRZ            1030
#define IDC_BUTTON_LOAD_INTERACTION2    1030
#define IDC_BUTTON_SELECTCANCEL_INTERACTION 1030
#define IDC_BUTTON_ADDLIGHT             1031
#define IDC_STATIC_PERIOD               1031
#define IDC_EDIT_SHADER_LIGHTDIFFUSER   1032
#define IDC_STATIC_POSITION             1032
#define IDC_EDIT_SHADER_LIGHTDIFFUSEG   1033
#define IDC_STATIC_POSITION2            1033
#define IDC_EDIT_SHADER_LIGHTDIFFUSEB   1034
#define IDC_STATIC_POSITION3            1034
#define IDC_EDIT_SHADER_LIGHTDIFFUSEA   1035
#define IDC_STATIC_POSITION4            1035
#define IDC_EDIT_SHADER_LIGHTAMBIENTR   1036
#define IDC_STATIC_PERIOD2              1036
#define IDC_EDIT_SHADER_LIGHTAMBIENTG   1037
#define IDC_STATIC_POSITION5            1037
#define IDC_EDIT_SHADER_LIGHTAMBIENTB   1038
#define IDC_STATIC_POSITION6            1038
#define IDC_EDIT_SHADER_LIGHTAMBIENTA   1039
#define IDC_STATIC_POSITION7            1039
#define IDC_EDIT_SHADER_LIGHTSPECULARR  1040
#define IDC_STATIC_POSITION8            1040
#define IDC_EDIT_SHADER_LIGHTSPECULARG  1041
#define IDC_STATIC_PERIOD3              1041
#define IDC_EDIT_SHADER_LIGHTSPECULARB  1042
#define IDC_STATIC_POSITION9            1042
#define IDC_EDIT_SHADER_LIGHTSPECULARA  1043
#define IDC_STATIC_PERIOD4              1043
#define IDC_SLIDER_LIGHTDIFFUSER        1044
#define IDC_STATIC_POSITION10           1044
#define IDC_SLIDER_LIGHTDIFFUSEG        1045
#define IDC_BUTTON_SELECTCANCEL_INTERACTION2 1045
#define IDC_BUTTON_PLAYER_CAMERA_ONOFF  1045
#define IDC_SLIDER_LIGHTDIFFUSEB        1046
#define IDC_SLIDER_LIGHTDIFFUSEA        1047
#define IDC_SLIDER_LIGHTAMBIENTR        1048
#define IDC_SLIDER_LIGHTAMBIENTG        1049
#define IDC_SLIDER_LIGHTAMBIENTB        1050
#define IDC_SLIDER_LIGHTAMBIENTA        1051
#define IDC_SLIDER_LIGHTSPECULARR       1052
#define IDC_SLIDER_LIGHTSPECULARG       1053
#define IDC_SLIDER_LIGHTSPECULARB       1054
#define IDC_SLIDER_LIGHTSPECULARA       1055
#define IDC_EDIT_SHADER_LIGHTRANGE      1056
#define IDC_EDIT_SHADER_VAR_FLOAT5      1057
#define IDC_BUTTON_ADDLIGHT2            1057
#define IDC_EDIT_SHADER_VAR_FLOAT6      1058
#define IDC_EDIT_SHADER_VAR_FLOAT7      1059
#define IDC_EDIT_SHADER_VAR_FLOAT8      1060
#define IDC_EDIT_SHADER_VAR_FLOAT9      1061
#define IDC_EDIT_SHADER_VAR_FLOAT10     1062
#define IDC_EDIT_SHADER_VAR_FLOAT11     1063
#define IDC_EDIT_SHADER_VAR_FLOAT12     1064
#define IDC_EDIT_SHADER_VAR_FLOAT13     1065
#define IDC_EDIT_SHADER_VAR_FLOAT14     1066
#define IDC_EDIT_SHADER_VAR_FLOAT15     1067
#define IDC_EDIT_SHADER_VAR_FLOAT16     1068
#define IDC_CHECK_SHADER_FOG            1069
#define IDC_EDIT_SHADER_SPOTLIGHT_MINANGLE 1070
#define IDC_CHECK_SHADER_LIGHTSHAFT     1070
#define IDC_EDIT_SHADER_SPOTLIGHT_MAXANGLE 1071
#define IDC_SLIDER_SPOTLIGHT_MINANGLE   1072
#define IDC_SLIDER_SPOTLIGHT_MAXANGLE   1073
#define IDC_EDIT_SHADER_SELECTVARNUM    1074
#define IDC_EDIT_SHADER_SELECTVARMIN    1075
#define IDC_EDIT_SHADER_SELECTVARMAX    1076
#define IDC_SLIDER_SELECTNUMVALUE       1077
#define IDC_EDIT_SHADER_SELECTVARUE     1078
#define IDC_BUTTON_SHADER_DELETES_SHADERVAR 1079
#define IDC_RADIO_LIGHTMODE1            1080
#define IDC_RADIO_LIGHTMODE2            1081
#define IDC_TREE1                       1084
#define IDC_EDIT_LIGHTGROUPNAME         1085
#define IDC_CHECK_PICKINGYPOSTYPE       1086
#define IDC_CHECK_SHOWLIGHTDEBUG        1087
#define IDC_CHECK_LIGHTPICKING          1088
#define IDC_EDIT_YPOSPLUS               1089
#define IDC_CHECK_CAMRUNMODE            1091
#define IDC_BUTTON2                     1092
#define IDC_CHECK_LIGHTGROUPONOFF       1093
#define IDC_BUTTON29                    1093
#define IDC_BUTTON12                    1097
#define IDC_BUTTON7                     1098
#define IDC_BUTTON8                     1099
#define IDC_BUTTON9                     1100
#define IDC_BUTTON10                    1101
#define IDC_BUTTON11                    1102
#define IDC_BUTTON14                    1103
#define IDC_BUTTON13                    1104
#define IDC_BUTTON15                    1105
#define IDC_BUTTON16                    1106
#define IDC_CHECK_LIGHTONOFF            1107
#define IDC_BUTTON18                    1108
#define IDC_BUTTON19                    1109
#define IDC_BUTTON17                    1110
#define IDC_BUTTON_SHOW_COLORDIALOG     1111
#define IDC_COMBO1                      1112
#define IDC_COMBO_PLAYERTYPE            1112
#define IDC_COMBO_MAPKIND               1112
#define IDC_COMBO_STAGETYPE             1112
#define IDC_BUTTON_SHOW_AMBIENTCOLORDIALOG2 1113
#define IDC_COMBO2                      1113
#define IDC_COMBO_MONSTERTYPE           1113
#define IDC_BUTTON_SHOW_SPECULARCOLORDIALOG3 1114
#define IDC_BUTTON3                     1114
#define IDC_BUTTON_CREATEPLAYER         1114
#define IDC_BUTTON4                     1115
#define IDC_BUTTON_CREATEMONSTER        1115
#define IDC_MAP_RENDER_REFRESH          1115
#define IDC_EDIT1                       1116
#define IDC_EDIT_PL_ANI_INDEX           1116
#define IDC_LIST1                       1117
#define IDC_LIST_OPTION                 1117
#define IDC_LIST2                       1118
#define IDC_LIST_DETAILDATA             1118
#define IDC_BUTTON5                     1119
#define IDC_EDIT_PL_ADD_EVENT_ANIPOS    1119
#define IDC_BUTTON_CREATE_MAP           1119
#define IDC_EDIT2                       1120
#define IDC_EDIT_PL_EVENT_ANIPOS        1120
#define IDC_BUTTON6                     1121
#define IDC_BUTTON_PL_CHANGE_ANISPEED   1121
#define IDC_BUTTON20                    1122
#define IDC_BUTTON_PL_CHANGE_ANIINDEX   1122
#define IDC_EDIT6                       1123
#define IDC_EDIT_MON_ANI_INDEX          1123
#define IDC_EDIT3                       1124
#define IDC_EDIT_PL_EVENT_OPTION        1124
#define IDC_EDIT4                       1125
#define IDC_EDIT_PL_EVENT_DETAILDATA    1125
#define IDC_BUTTON21                    1126
#define IDC_EDIT_PL_ADD_EVENT_DETAILDATA 1126
#define IDC_BUTTON22                    1127
#define IDC_EDIT_PL_MODIFY_EVENT_OPTION 1127
#define IDC_EDIT5                       1128
#define IDC_EDIT_PL_EVENT_CUROPTION     1128
#define IDC_BUTTON23                    1129
#define IDC_BUTTON_MON_CHANGE_ANISPEED  1129
#define IDC_BUTTON24                    1130
#define IDC_BUTTON_MON_CHANGE_ANIINDEX  1130
#define IDC_EDIT7                       1131
#define IDC_EDIT_MON_START_ANITIME      1131
#define IDC_BUTTON25                    1132
#define IDC_BUTTON_MODIFY_MON_START_ANITIME 1132
#define IDC_EDIT_MON_START_ANITIME2     1133
#define IDC_EDIT8                       1134
#define IDC_EDIT_BETWEENANGLE_PL_TO_MON 1134
#define IDC_CHECK2                      1135
#define IDC_CHECK_PL_CHANGE_ANGLE       1135
#define IDC_BUTTON26                    1136
#define IDC_BUTTON_MODIFY_BETWEENANGLE_PL_TO_MON 1136
#define IDC_BUTTON27                    1137
#define IDC_BUTTON_RESET_MON_START_ANITIME 1137
#define IDC_CHECK3                      1138
#define IDC_CHECK_MON_CHANGE_ANGLE      1138
#define IDC_CHECK4                      1139
#define IDC_CHECK_PL_CHANGE_POS         1139
#define IDC_CHECK5                      1140
#define IDC_CHECK_MON_CHANGE_POS        1140
#define IDC_EDIT9                       1141
#define IDC_EDIT_BETWEENDIST_PL_TO_MON  1141
#define IDC_BUTTON28                    1142
#define IDC_BUTTON_MODIFY_BETWEENDIST_PL_TO_MON 1142
#define IDC_EDIT_BETWEENANGLE_PL_TO_MON2 1143
#define IDC_BUTTON_START_ANIMATION      1144
#define IDC_BUTTON_STOP_ANIMATION       1145
#define IDC_BUTTON_START_INTERACTION    1146
#define IDC_EDIT_BETWEENDIST_PL_TO_MON2 1147
#define IDC_LIST_INTERACTION            1148
#define IDC_EDIT_INTERACTIONNAME        1149
#define IDC_CHECK_DIFFUSESPECULARSAMEPOWER 1150
#define IDC_BUTTON_PL_CHANGE_POS        1151
#define IDC_CHECK_DIFFUSESPECULARSAMEPOWER2 1151
#define IDC_CHECK_FLOATINGPOWER         1151
#define IDC_BUTTON_MODIFY_STAGESHADERDATA 1151
#define IDC_BUTTON_PL_CHANGE_ANGLE      1152
#define IDC_BUTTON_MON_CHANGE_POS       1153
#define IDC_BUTTON_MON_CHANGE_ANGLE     1154

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        314
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1152
#define _APS_NEXT_SYMED_VALUE           314
#endif
#endif
