#pragma once

#define LOAD_THREAD_MAX_SIZE 20

const unsigned int BACKSIZEX = 1920;
const unsigned int BACKSIZEY = 1080;

const float FAR_DISTANCE = 1000.f;
const float NEAR_DISTANCE = 0.2f;

//enum CHAR_TYPE { CHAR_TYPE_MONSTER, CHAR_TYPE_PLAYER, CHAR_TYPE_END };
enum SCENETYPE {SCENE_STATIC,SCENE_VIDEO, SCENE_LOGO, SCENE_STAGE, SCENE_BOSS, SCENE_END};
enum LOADTYPE { LOAD_Donatello, LOAD_Leonardo, LOAD_Michelangelo, LOAD_Raphael, 
	LOAD_BASIC_STAGE, LOAD_SHADER, LOAD_TEX_UI, LOAD_STAGE1_MONSTER , LOAD_EFFECT };


enum PLAYER_TYPE {
	PLAYER_Donatello,
	PLAYER_Leonardo,
	PLAYER_Michelangelo,
	PLAYER_Raphael,
	PLAYER_None,
}; //By.KJW 

enum SUBJECTMESSAGE //By.PSH 
{	
	MESSAGE_CURRENT_PLAYER_DATA,
	MESSAGE_PLAYER_DATA,
	MESSAGE_CAMERA_DATA,
	MESSAGE_STATE_DATA,
	MESSAGE_PIZZA_DATA,
	MESSAGE_SHURIKEN_DATA,
	MESSAGE_COMBO_DATA
};
